name: Create github release using cargo

on:
    push:
        branches: ["main", "wip", "ci"]
    pull_request:
        branches: ["main"]

jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Build
            run: cargo build --release

          - name: Release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                tag_name: ${{ github.ref }}
                prerelease: true
                files: target/release/rv-format

