name: Create ubuntu release

on:
    push:
        branches: ["main"]
        tags: ["v*"]

jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                submodules: true

          - name: Build
            run: cargo build --release

          - name: Release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                tag_name: ignp ${{ github.ref }}
                prerelease: true
                files: target/release/rv-format

