name: Run tests

on:
  push:
    branches: ["main", "wip"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout src
        uses: actions/checkout@v3

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test
